// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Vitor.Models;

#nullable disable

namespace Vitor.Migrations
{
    [DbContext(typeof(AppDataContext))]
    partial class AppDataContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.4");

            modelBuilder.Entity("Vitor.Models.Folha", b =>
                {
                    b.Property<string>("folhaId")
                        .HasColumnType("TEXT");

                    b.Property<int>("Ano")
                        .HasMaxLength(4)
                        .HasColumnType("INTEGER");

                    b.Property<int>("Mes")
                        .HasMaxLength(2)
                        .HasColumnType("INTEGER");

                    b.Property<int>("Quantidade")
                        .HasColumnType("INTEGER");

                    b.Property<double>("Valor")
                        .HasColumnType("REAL");

                    b.Property<string>("funcionarioId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("folhaId");

                    b.ToTable("tabFolha");
                });

            modelBuilder.Entity("Vitor.Models.Funcionario", b =>
                {
                    b.Property<string>("funcionarioId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Cpf")
                        .IsRequired()
                        .HasMaxLength(11)
                        .HasColumnType("TEXT");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("funcionarioId");

                    b.ToTable("tabFuncionario");
                });
#pragma warning restore 612, 618
        }
    }
}
